# Generated by Django 5.1.6 on 2025-03-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
